### ISSUE TITLE
Story #1 - Rent a Game

### ISSUE THREAD

**Issue by fuchsiaberry** [Paretooptimal22/game-vault#1]
- [ ] landing page
- [ ] browse
- [ ] add filters
- [ ]  choose a game (see more game details)
- [ ] rent a game (and request rental time period
- [ ] redirect to confirm page

**Comment by Paretooptimal22** [comment]
- [ ] landing page
- [ ] browse
- [ ] add filters
- [ ] choose a game (see more game details)
- [ ] rent a game (and request rental time period
- [ ] redirect to confirm page

**Comment by jpblicer** [comment]
logic completed
